const GITHUB_PLATFORM = 'github'
const GITLAB_PLATFORM = 'gitlab'

const LOG_TYPE_SUCCESS = 'success'
const LOG_TYPE_ERROR = 'error'
const LOG_TYPE_WARNING = 'warning'
const LOG_TYPE_INFO = 'info'

const WORKFLOW_TYPE_BASIC = 'basic'
const WORKFLOW_TYPE_WITH_DP = 'with-dependabot'

const NODE_ENVIRONMENT = 'node'
const PHP_ENVIRONMENT = 'php'
const GO_ENVIRONMENT = 'go'

const TEMPLATE_PATH = '../../templates'

module.exports = {
  GITHUB_PLATFORM,
  GITLAB_PLATFORM,
  LOG_TYPE_SUCCESS,
  LOG_TYPE_ERROR,
  LOG_TYPE_WARNING,
  LOG_TYPE_INFO,
  WORKFLOW_TYPE_BASIC,
  WORKFLOW_TYPE_WITH_DP,
  NODE_ENVIRONMENT,
  PHP_ENVIRONMENT,
  GO_ENVIRONMENT,
  TEMPLATE_PATH
}
