version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: pnpm
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    reviewers:
      - '' # add your github username
    assignees:
      - '' # add your github username
    labels:
      - 'dependencies'
      - 'pnpm'
